version: '3.8'

services:
  backend:
    build: webService
    container_name: nestjs-backend-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: npm run start
    depends_on:
      - db

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: timescale-db-prod
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
