name: Apply Flyway Migrations On Staging Environment

on:
  push:
    branches:
      - main
    paths:
      - "flyway/migrations/*.sql"

jobs:
  migrate-db-trunk:
    runs-on: ubuntu-latest
    environment: "staging" # Uses selected GitHub environment
    env:
      SQL_AUTO_MIGRATE_ENABLED: ${{ vars.SQL_AUTO_MIGRATE_ENABLED || 'false' }} # Use GitHub environment variable with default

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Flyway Migrations in Docker
        if: env.SQL_AUTO_MIGRATE_ENABLED == 'true'
        run: |
          docker run --rm \
            -v $(pwd)/flyway/migrations:/flyway/sql \
            flyway/flyway:10 \
            -url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            migrate
