FROM ghcr.io/puppeteer/puppeteer:latest

WORKDIR /app
RUN chown -R pptruser:pptruser /app
USER pptruser
COPY --chown=pptruser:pptruser package*.json ./
RUN npm install
COPY --chown=pptruser:pptruser . .
RUN npx tsc
EXPOSE 3000
CMD ["node", "dist/server.js"]
