create table UsersListingsLinks (
    UserID INTEGER NOT NULL,
    ListingID INTEGER NOT NULL,
    DateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID, ListingID),
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY (ListingID) REFERENCES Listings(ID) ON DELETE CASCADE
)